### ISSUE TITLE
text bubbles should go above everything

### ISSUE THREAD

**Issue by ju-de** [jz-feng/tojam22#1]
![image](https://user-images.githubusercontent.com/7605884/168498947-b1915d3e-0461-4780-be6f-4b1e3017f2b0.png)

**Comment by ju-de** [comment]
reopening

**Comment by jz-feng** [comment]
[7de0da5](https://github.com/jz-feng/animart/commit/7de0da5e937979cd0ebe64f9b06d0eb02b34021e)
